framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: 'portfolio_app'

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        app: cache.adapter.filesystem

        # Namespaced pools use the above "app" backend by default
        pools:
            app.cache:
                adapter: cache.app
                default_lifetime: 3600
            system.cache:
                adapter: cache.system
                default_lifetime: 3600
