# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        name: MOURCHAD_SESSION

    #esi: true
    #fragments: true

    rate_limiter:
        contact_form:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
